# Generated by Django 3.2.16 on 2023-01-16 15:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usershopcart',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь корзины',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user_cart', to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='tagsrecipe',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='tagsrecipe',
            name='tags',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to='recipes.tags'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='author',
            field=models.ForeignKey(
                help_text='Автор рецепта',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='author', to=settings.AUTH_USER_MODEL,
                verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(
                help_text='Ингредиент рецепта', related_name='ingredients',
                through='recipes.IngredientAmount', to='recipes.Ingredients',
                verbose_name='Ингредиент'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(
                help_text='Тег рецепта', related_name='tags',
                through='recipes.TagsRecipe', to='recipes.Tags',
                verbose_name='Тег'),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='ingredient',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='ingredient', to='recipes.ingredients'),
        ),
        migrations.AddField(
            model_name='ingredientamount',
            name='recipe',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='resipe_ingredient', to='recipes.recipe'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='recipe',
            field=models.ForeignKey(
                help_text='рецепт пользователя',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='favorite_recipe', to='recipes.recipe',
                verbose_name='рецепт'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(
                help_text='Пользователь корзины',
                on_delete=django.db.models.deletion.CASCADE,
                related_name='user', to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь'),
        ),
        migrations.AddConstraint(
            model_name='usershopcart',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_shop_cart'),
        ),
        migrations.AddConstraint(
            model_name='recipe',
            constraint=models.UniqueConstraint(
                fields=('name', 'author'), name='unique_recipe_author_name'),
        ),
        migrations.AddConstraint(
            model_name='ingredientamount',
            constraint=models.UniqueConstraint(
                fields=('recipe', 'ingredient'),
                name='recipe_ingredient_constrain'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(
                fields=('user', 'recipe'), name='unique_favorite'),
        ),
    ]
